"""
ModelLog: Stores logs generated by ML models for cloud integration and dashboard summary.
"""
from sqlalchemy import Column, String, DateTime, JSON, Integer
from datetime import datetime
from app.config.database import Base

class ModelLog(Base):
    __tablename__ = "model_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False)
    model_name = Column(String, nullable=False)
    log_level = Column(String, nullable=False)
    message = Column(String, nullable=False)
    extra = Column(JSON, nullable=True)
